### ISSUE TITLE
Résultats différents

### ISSUE THREAD

**Issue by seb-L8L** [cnumr/GreenIT-Analysis#15]
Bonjour,
En testant le même site nous avons des résultats qui diffèrent d'un navigateur à l'autre, ou d'un ordinateur à l'autre. Nous n'arrivons pas à comprendre ce qui peut poser problème.

Ordi 1 - Chrome
![Capture du 2020-05-12 16-02-54](https://user-images.githubusercontent.com/64834183/81702628-d427a180-946b-11ea-970d-d08992db3421.png)

Ordi 1 - FireFox
![Capture du 2020-05-12 16-03-28](https://user-images.githubusercontent.com/64834183/81702675-e30e5400-946b-11ea-9a28-bd9a92c09417.png)

Ordi 2 - Chrome
![Capture d’écran 2020-05-12 à 16 02 40](https://user-images.githubusercontent.com/64834183/81702824-13ee8900-946c-11ea-87fd-fa9dcef7ae23.png)

Une idée ?
Merci !!

**Comment by didierfred** [comment]
Bonjour,

Sur la documentation https://github.com/cnumr/GreenIT-Analysis , vous trouverez dans la rubrique "Utiliser l'extension / Quelques points de vigilance ", les points à vérifier

Je pense en particulier à :  bien veiller à ouvrir le panel développeur avant d'aller sur le site à tester (Touche F12) . Sur le test 1 , on a le nombre de requêtes à 0 , ce qui me laisse supposer que l'outil a été ouvert une fois le site affiché . Le résultat est donc dans ce cas faux.

Si le site que vous analysez est accessible depuis internet , je peux aussi aller faire quelques tests 

Frédéric

**Comment by seb-L8L** [comment]
Effectivement les tests sont bcp plus cohérents et constants en procédant... comme indiqué dans la doc :( RTFM syndrome! :)
Merci bien pour la réponse rapide, et bravo pour ce dév !
FYI : le site testé est lesoctetslibres.com
