### ISSUE TITLE
Enregistrement impossible

### ISSUE THREAD

**Issue by Kilinah** [cnumr/GreenIT-Analysis#30]
Bonjour,
Impossible pour moi d'enregistrer une analyse. J'ai beau cliquer sur le bouton "sauver une analyse", rien ne se passe et rien n'apparait dans l'historique. :(
Une idée d'où vient le soucis?

**Comment by didierfred** [comment]
Bonjour , 
vous êtes sur quel navigateur et quelle est sa version ?

**Comment by Kilinah** [comment]
Bonjour,
Je suis sur Chrome, dernière version (Version 90.0.4430.72) :)

**Comment by didierfred** [comment]
Pourriez vous me fournir les logs de la console du navigateur ?

Pour cela :  
-  Sur l'ecran du plugin faire un click droit et menu "inspecter" 
-  Aller dans le menu "console" de la fenêtre qui s'affiche 
- Lancer une analyse puis clicker plusieurs fois sur sauver l'analyse 
- Faites un copier/coller de ce qui s'est affiché dans la console

**Comment by Kilinah** [comment]
![image](https://user-images.githubusercontent.com/82610970/115202287-8c3ae100-a0f6-11eb-8a4c-a10d505fc0a9.png)

**Comment by didierfred** [comment]
Au vu de  ce que je vois dans votre console , je pense que vous avez ouvert la console de la page web et pas la console associée  au plugin (j'ait fait un test sur mon PC avec ce site) . Il faut bien faire attention de clicker dans la page du plugin pour accéder au menu inspecter .

An complément de cette copie d'ecran , une fois la console ouverte pouvez me faire une copie d'ecran de l'onglet application / menu local storage / lien chrome-extension://... , à l'image de la copie d'ecran ci-après :

![image](https://user-images.githubusercontent.com/34892849/115443920-2cd2f300-a214-11eb-9958-05f378fb5ed2.png)

Après copie ,  s'il y a bien des valeurs comme sur la copie d'ecran , pouvez vous essayez de les effacer (click droit sur la valeur + menu clear) . Et après retenter de sauvegader une analyse . (Les analyses sont stockées dans le local storage , il se peut qu'il y ai des données corrompues qui empeche le bon fonctionnement) 

Par ailleurs , j'ai fait des tests avec strictement la même version que vous et je n'ai pas de pb (sous linux et sous windows)

**Comment by Kilinah** [comment]
Bonjour,
Voici la capture d'écran. par contre, je n'ai aucun lien Chrome dans le local storage. Je pense que mon problème doit venir de là, non?
![image](https://user-images.githubusercontent.com/82610970/115674574-1630b700-a34e-11eb-98cf-51463e5c8891.png)

**Comment by didierfred** [comment]
en fait vous avez ouvert les devtools associés au site https://www.kpicreativ.fr et pas ceux associés au plugin.

A partir de votre vue d'ecran , aller dans greenIt et depuis cet ecran click droit et menu "inspecter" , et là vous allez ouvrir la vue pour le plugin

**Comment by Kilinah** [comment]
Ah ok...
Bon, j'ai bien les liens Chrome mais les valeurs sont vides. Par contre, j'ai des messages d'erreur dans la console.
![image](https://user-images.githubusercontent.com/82610970/115692061-eccc5700-a35e-11eb-8e67-9f6a60dab45e.png)
![image](https://user-images.githubusercontent.com/82610970/115692096-f655bf00-a35e-11eb-92e5-5e15255f2048.png)
![image](https://user-images.githubusercontent.com/82610970/115692166-066d9e80-a35f-11eb-83c7-1e73eb0a5bfd.png)

**Comment by Kilinah** [comment]
Les  liens chrome sont vides :( Par contre, j'ai des messages d'erreur dans la console
![image](https://user-images.githubusercontent.com/82610970/115692357-3321b600-a35f-11eb-93ee-a3dba28ef87b.png)
![image](https://user-images.githubusercontent.com/82610970/115692405-3d43b480-a35f-11eb-95ca-7ac611c5f60a.png)
![image](https://user-images.githubusercontent.com/82610970/115692435-446ac280-a35f-11eb-885b-4cb2f72c2d7b.png)

**Comment by didierfred** [comment]
Je viens de faire qq tests et j'arrive à reproduire le pb . Il s'agit de vos réglages de sécurité 
Si vous cocher l'option "bloquer les cookies tiers"  (par defaut c'est: "bloquer les cookies tiers en navigation privé" , cf vue d'ecran) alors le plugin n'est plus autorisé à accédér à la fonction local storage qui permet l'enregistrement des analyses.

![image](https://user-images.githubusercontent.com/34892849/115711245-93baee00-a373-11eb-9d38-766903d979c9.png)

Je n'ai pas réussi à le faire fonctionner en jouant avec les exceptions (config en base de page) 

A ce stade , je ne vois qu'une solution , autoriser les cookies lorsque vous utilisez le plugin  et réactiver à postériori le filtrage des cookies . Attention pour que les modifications soient prises en compte il faut quitter le panel developpeur (devtools) et le réouvrir.

**Comment by Kilinah** [comment]
J'ai débloquer les cookies tiers et ça refonctionne normalement. Merci beaucoup pour l'aide apportée! :)
