### ISSUE TITLE
[Comptage des inline styles] Images <svg>

### ISSUE THREAD

**Issue by m3uusi** [cnumr/GreenIT-Analysis#34]
Bonjour,

Lors de l'utilisation de l'extension, les balises styles contenues au sein des images SVG sont comptabilisées comme des feuilles de syle inline.

Exemple actuel : 
https://lowtechlab.org/en , 3 feuilles de style inline sont détectées par le plugin mais elles font toutes les 3 parties d'une image SVG.

Je ne connais pas les normes de calcul pour les notes de l'écoindex mais je pense qu'on pourrait supposer que les balises <style> inclues dans les SVG ne sont pas des feuilles de style inline pour la page elle-même.

Code de reproduction (Compte 3 inline style) :
```<!doctype html>
<html>
  <head>
    <title>This is the title of the webpage!</title>
  </head>
  <body>
  <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
  <style>
    circle {
      fill: gold;
      stroke: maroon;
      stroke-width: 2px;
    }
  </style>

  <circle cx="5" cy="5" r="4"></circle>
</svg>
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
  <style>
    circle {
      fill: gold;
      stroke: maroon;
      stroke-width: 2px;
    }
  </style>

  <circle cx="5" cy="5" r="4"></circle>
</svg>
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
  <style>
    circle {
      fill: gold;
      stroke: maroon;
      stroke-width: 2px;
    }
  </style>

  <circle cx="5" cy="5" r="4"></circle>
</svg>
  </body>
</html>
```

Cordialement,

**Comment by didierfred** [comment]
je suis d'accord 
 PR mergé
