### ISSUE TITLE
Issue? Current implementation gives EcoIndex between -5 and 94 instead of 0 to 99

### ISSUE THREAD

**Issue by Olivier-Descout** [cnumr/GreenIT-Analysis#61]
Hi,
I suspect there is an issue (or an inconsistency against the Ecoindex specification) in the current EcoIndex implementation located in the file `ecoIndex.js`.

As it is currently computed, EcoIndex value is between -5 and 94 rather than between 0 and 99 :
- The smallest possible HTML page (`<html></html>` containing 3 DOM objects (page + empty header + empty body), generating 1 HTTP request and being 13-byte long) gets an EcoIndex equal to 94.00 (if rounded to 2 digits after the decimal point).
- The theorically-worst HTML page (594,601 DOM objects; 3,920 HTTP requests; 223,213 kilobytes) gets a EcoIndex equal to -5.

[Rachel Pellin](https://github.com/rachelwe)'s EcoIndex simulator (https://rachelwe.github.io/Simulateur-ecoindex/), which uses `ecoIndex.js` current implementation, helps highligting this behaviour:
- the returned EcoIndex for a (theorical) HTML page with 0 DOM element, 0 HTTP request, 0-byte long gives an EcoIndex of 95 instead of 100.
- the returned EcoIndex for the smallest HTML page described above if 94 instead of 99.
- the returned EcoIndex for the worst-possible HTML page is -5 instead of 0.
- if you compute the EcoIndex while using the worst value for one parameter and zero for the two others, the returned EcoIndex is lower than expected: for instance, the combination of 594,601 DOM objects, 0 HTTP requests and 0 kB gives an EcoIndex of 47.5 instead of the expected 50.

In my opinion, the issue lies in the `calculateIndex` function, which should return:
`            return ((i - 1) + (value - quantiles[i - 1]) / (quantiles[i] - quantiles[i - 1]));`
and
`    return quantiles.length - 1;`
instead of:
`            return (i + (value - quantiles[i - 1]) / (quantiles[i] - quantiles[i - 1]));`
and
`    return quantiles.length;`

If such a change were to be made, the grade computation would obviously have to be also altered, by adding 5 to every threshold:
`case score >= 80: return 'A';` _// instead of 75_
`case score >= 70: return 'B';` _// instead of 65_
`...`
`case score >= 10: return 'F';` _// instead of 5_

Best Regards,
Olivier Descout

**Comment by didierfred** [comment]
Yes you are right , following a pull request , i worked on a correction regarding this topic a year ago an never merged it : https://github.com/cnumr/GreenIT-Analysis/commit/350ca5a16df4102edbac1531160d31d5632b997b

I will check

**Comment by bordage** [comment]
Thanks Olivier (and Rachel) for this point. IT's obvious we should implent this patch asap. The good news is that this will have a negligeable side effect to already computed EcoIndex evaluation.

**Comment by didierfred** [comment]
The patch is integrated in release 3.1.0 available on chrome web store and firefox add ons

**Comment by Olivier-Descout** [comment]
Merci ! 
 
  Le sam., sept. 10, 2022 à 18:04, ***@***.***> a écrit:   


The patch is integrated in release 3.1.0 available on chrome web store and firefox add ons
