### ISSUE TITLE
Nombre d'éléments du DOM très importants

### ISSUE THREAD

**Issue by bordage** [cnumr/GreenIT-Analysis#65]
Bonjour,

Je pense qu'il y a un bug dans la dernière version de l'extension. 
Config : W10, FF 106.03

Lors de l'enregistrement d'un parcours utilisateurs classique, tout se passe bien (nombre d'éléments du DOM cohérent). Mais arrivé sur un formulaire, l'extension GIT-Analysis me remonte 26501 éléments du DOM alors qu'on a entre 500 et 800 sur les autres pages.

Des stagiaires en formation ont également eu cette situation sur d'autres sites à partir d'autres configurations (autres OS et navigateur).

Cf. par exemple ce dump avec la valeur 26501 dans la deuxième ligne : 
Date;Url;Nombre requêtes;Taille(kb);Taille du dom;GES;Eau;ecoIndex;Note
05/11/2022 10:52:17;"https://www.techchallenger.fr/inscription/";187;8824;26501;2.85;4.28;7.42;G
05/11/2022 10:51:36;"https://www.techchallenger.fr/reglement-du-concours/";85;2965;750;2.21;3.32;39.32;E
05/11/2022 10:51:26;"https://www.techchallenger.fr/conferences/";86;3016;585;2.11;3.16;44.62;D
05/11/2022 10:51:14;"https://www.techchallenger.fr/";91;3316;740;2.24;3.36;37.95;E

**Comment by didierfred** [comment]
Bonjour ,

Pour la page d'inscription, ça correspond bien au nombre d'élements du dom (svg déduis) , je ne vois pas de bug à ce niveau . 

Sur ce point le code de l'extension est très simple et donc peu sujet à bug par ailleurs.

J'ai fait tourné un bout de code pour avoir plus de détail sur le contenu du DOM par tags:

Pour les tags les plus présent : 
div : 8843
span : 8100
li : 4276 
option : 3464

![image](https://user-images.githubusercontent.com/34892849/200166291-0b92c074-218d-4946-bcdc-e9937023b31a.png)

**Comment by bordage** [comment]
Merci Fred pour ton retour et désolé pour le dérangement.
