### ISSUE TITLE
La source de données utilisées pour le calcul de l'EcoIndex diffère entre Chrome et Firefox

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/GreenIT-Analysis#74]
On m'a remonté hier un problème d'implémentation critique :
- Sur Chrome (et consorts), le calcul de l'EcoIndex porte sur les **données transférées** ;
- Sur Firefox, le calcul de l'EcoIndex porte sur les **données décodées**.

Le score qui en découle d'un écosystème à un autre n'est donc pas comparable (ni même valide sur Firefox, puisque ce sont il me semble les données transférées, relatives au tiers 2, qui doivent être prises en compte).

Il est possible de récupérer à la fois les données transférées et décodées sur l'ensemble des navigateurs :
- L'en-tête de réponse `bodySize` peut être utilisé pour Firefox ;
- L'en-tête de réponse `_transferSize` peut être utilisé pour Chrome (et consorts). À noter que c'est Chrome qui ici ne respecte pas la spécification HttpArchive (HAR).

À voir si cela doit (peut) être corrigé avant la sortie d'une nouvelle version.
La documentation devrait sinon expliciter que Firefox ne devrait pas être utilisé à cause de cette implémentation.

**Comment by didierfred** [comment]
J'ai corrigé le code et je viens de pousser la nouvelle version (3.1.4) sur le store firefox, ca devrait être disponible sous peu

**Comment by didierfred** [comment]
Nouvelle version disponible

**Comment by JulienWilhelm** [comment]
Quelle réactivité !
Merci pour la communauté, @didierfred !
